#ifndef _HKM_
#define _HKM_

#define HKM_FAIL		((DWORD)-1) //失败

#define HDT_ALL		0 //全部模式
#define HDT_KM		1 //键鼠模式
#define HDT_KEY		2 //键盘模式
#define HDT_MOUSE	3 //鼠标模式

#define HMT_REL		1 //相对坐标鼠标
#define HMT_ABS		2 //绝对坐标鼠标
#define HMT_RA		3 //相对坐标鼠标+绝对坐标鼠标

#define HDEMI_POS		0x01 //屏幕坐标
#define HDEMI_MOVE		0x02 //鼠标移动方式
#define HDEMI_WHEEL		0x03 //鼠标滚轮滚动方式
#define HDEMI_STR		0x04 //输出字符串编码
#define HDEMI_SYNC		0x05 //键盘、鼠标同步方式
#define HDEMI_RND		0x06 //延时随机方式
#define HDEMI_FUN		0x20 //函数的参数或者返回值的字符串类型

#define HDEPM_PHYSICAL	0x00 //物理坐标
#define HDEPM_VIRTUAL	0x01 //虚拟坐标
#define HDEMM_DEFAULT	0x00 //默认鼠标移动方式
#define HDEMM_QUICK		0x01 //鼠标快速移动
#define HDEMM_ABS		0x02 //鼠标绝对移动
#define HDEWM_SIM		0x00 //鼠标滚轮仿真滚动
#define HDEWM_QUICK		0x01 //鼠标滚轮快速滚动
#define HDESM_ANSI		0x00 //输出字符串ANSI编码方式
#define HDESM_UNICODE	0x01 //输出字符串UNICODE编码方式
#define HDESM_ANSI2		0x02 //输出字符串ANSI编码2方式
#define HDESM_UNICODE2	0x03 //输出字符串UNICODE编码2方式
#define HDEAM_SYNC		0x00 //键盘鼠标操作同步
#define HDEAM_KAS		0x01 //键盘操作异步
#define HDEAM_MAS		0x02 //鼠标操作异步
#define HDERM_UFT		0x00 //延时随机均匀分布
#define HDERM_LITTLE	0x01 //延时随机偏小分布
#define HDEFM_UNICODE	0x00 //函数的参数或者返回值的字符串使用UNICODE编码
#define HDEFM_ANSI		0x01 //函数的参数或者返回值的字符串使用ANSI编码

#define KBD_NUM_LOCK	0 //NumLock指示灯
#define KBD_CAPS_LOCK	1 //CapsLock指示灯
#define KBD_SCROLL_LOCK	2 //ScrollLock指示灯

#define CKM_CHS			0x01 //检查按键，返回包含中文的信息
#define CKM_MOUSE		0x02 //检查按键，返回包含被按下的鼠标键信息
#define CKM_ANSI		0x04 //检查按键，返回的字符串使用ANSI编码

#ifdef __cplusplus
extern "C" {
#endif

DECLSPEC_IMPORT DWORD WINAPI HKMGetVersion(void);
DECLSPEC_IMPORT BOOL WINAPI HKMDisableDpi(void);
DECLSPEC_IMPORT int WINAPI HKMIsDisableDpi(void);
DECLSPEC_IMPORT DWORD WINAPI HKMSearchDevice(DWORD dwVid, DWORD dwPid, DWORD dwDeviceType);
DECLSPEC_IMPORT DWORD WINAPI HKMSearchDevice2(DWORD dwVid, DWORD dwPid, DWORD dwSN, DWORD dwDeviceType);
DECLSPEC_IMPORT LPVOID WINAPI HKMOpen(DWORD dwDeviceId);
DECLSPEC_IMPORT LPVOID WINAPI HKMOpen2(DWORD dwDeviceId1,DWORD dwDeviceId2);
DECLSPEC_IMPORT BOOL WINAPI HKMIsOpen(LPVOID lpHKMData,DWORD dwFlags);
DECLSPEC_IMPORT BOOL WINAPI HKMClose(LPVOID lpHKMData);
DECLSPEC_IMPORT DWORD WINAPI HKMGetSerialNumber(LPVOID lpHKMData,BOOL bMouse);
DECLSPEC_IMPORT DWORD WINAPI HKMGetMouseMode(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMIsKeyBusy(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMIsMouseBusy(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMGetKeyboardLEDState(LPVOID lpHKMData,DWORD dwIndex);
DECLSPEC_IMPORT BOOL WINAPI HKMGetCursorPos(LPVOID lpHKMData,LPLONG lpX,LPLONG lpY);
DECLSPEC_IMPORT DWORD WINAPI HKMGetCursorPos2(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMSetMode(LPVOID lpHKMData,DWORD dwIndex,DWORD dwMode);
DECLSPEC_IMPORT BOOL WINAPI HKMSetKeyInterval(LPVOID lpHKMData,DWORD dwMinTime,DWORD dwMaxTime);
DECLSPEC_IMPORT BOOL WINAPI HKMSetMouseInterval(LPVOID lpHKMData,DWORD dwMinTime,DWORD dwMaxTime);
DECLSPEC_IMPORT BOOL WINAPI HKMSetAbsMouseScrnRes(LPVOID lpHKMData,long lWidth,long lHeight);
DECLSPEC_IMPORT BOOL WINAPI HKMSetMousePosPrecision(LPVOID lpHKMData,DWORD dwPrecision);
DECLSPEC_IMPORT BOOL WINAPI HKMSetMouseMoveTimeout(LPVOID lpHKMData,DWORD dwTimeout);
DECLSPEC_IMPORT BOOL WINAPI HKMSetMousePosMaxOffset(LPVOID lpHKMData,DWORD dwOffset);
DECLSPEC_IMPORT BOOL WINAPI HKMKeyPress(LPVOID lpHKMData,LPCWSTR lpKeyName);
DECLSPEC_IMPORT BOOL WINAPI HKMKeyDown(LPVOID lpHKMData,LPCWSTR lpKeyName);
DECLSPEC_IMPORT BOOL WINAPI HKMKeyUp(LPVOID lpHKMData,LPCWSTR lpKeyName);
DECLSPEC_IMPORT BOOL WINAPI HKMMoveTo(LPVOID lpHKMData,long nX,long nY);
DECLSPEC_IMPORT BOOL WINAPI HKMMoveR(LPVOID lpHKMData,long nX,long nY);
DECLSPEC_IMPORT BOOL WINAPI HKMMoveR2(LPVOID lpHKMData,long nX,long nY);
DECLSPEC_IMPORT BOOL WINAPI HKMMoveRP(LPVOID lpHKMData,long nX,long nY);
DECLSPEC_IMPORT BOOL WINAPI HKMLeftClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMRightClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMMiddleClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMLeftDoubleClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMRightDoubleClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMMiddleDoubleClick(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMLeftDown(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMRightDown(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMMiddleDown(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMLeftUp(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMRightUp(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMMiddleUp(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMMouseWheel(LPVOID lpHKMData,long nCount);
DECLSPEC_IMPORT BOOL WINAPI HKMMouseWheelP(LPVOID lpHKMData,long nCount);
DECLSPEC_IMPORT BOOL WINAPI HKMReleaseKeyboard(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMReleaseMouse(LPVOID lpHKMData);
DECLSPEC_IMPORT BOOL WINAPI HKMOutputString(LPVOID lpHKMData,LPCWSTR lpString);
DECLSPEC_IMPORT BOOL WINAPI HKMDelayRnd(LPVOID lpHKMData,DWORD dwMinTime,DWORD dwMaxTime);
DECLSPEC_IMPORT LPWSTR WINAPI HKMCheckPressedKeys(DWORD dwFlags,LPDWORD lpLength);
DECLSPEC_IMPORT BOOL WINAPI HKMFreeData(LPVOID lpData);
DECLSPEC_IMPORT BOOL WINAPI HKMVerifyUserData(LPVOID lpHKMData,LPCWSTR lpString,BOOL bMouse);
DECLSPEC_IMPORT BOOL WINAPI HKMIsOSMouseAccelerateEnabled(void);
DECLSPEC_IMPORT BOOL WINAPI HKMEnableOSMouseAccelerate(BOOL bEnable,BOOL bSave);
DECLSPEC_IMPORT int WINAPI HKMGetOSMouseSpeed(void);
DECLSPEC_IMPORT BOOL WINAPI HKMSetOSMouseSpeed(int nSpeed,BOOL bSave);

#ifdef __cplusplus
}
#endif

#endif //_HKM_
